- name: VideoDojo
  image: hostVideoDojo.jpg
  language: EN
  channel: "https://www.youtube.com/@VideoDojoPro"
- name: TACTY
  image: hostTacty.jpg
  language: JP
  channel: "https://www.youtube.com/@tactylabo"
- name: jJae Studio
  image: hostjJae.jpg
  language: EN
  channel: "https://www.youtube.com/@jJaeStudio"